### ISSUE TITLE
cannot read configuration file!

### ISSUE THREAD

**Issue by dealy663** [Jeija/gtkterm#10]
I upgraded from ubuntu 16 to 18.04 yesterday. I had several gtkterm configs in a .gtktermrc file. After the upgrade gtkterm always gives me an error when I try to load a configuration: Cannot read configuration file!

It also appears that the .gtktermrc file isn't being updated when I try to save a configuration. This is version 1.0 according to the help | about screen.

Any idea how I can save and reuse my configurations?

Thanks, Derek

**Comment by wvdakker** [comment]
Please remove the .gtktermrc and start gtkterm again. New configfile will be created.
It seems the config-file from the older version is not compatiblie with this version.
Missing parameters will prevent loading the config.
