### ISSUE TITLE
compile error since adding device monitor

### ISSUE THREAD

**Issue by ddmesh** [Jeija/gtkterm#16]
I get the following compile error, since device monitoring is added.
perhaps "configure" does not check the requirements for libudev?
```
CC       gicon.o
CC       device_monitor.o
device_monitor.c:21:10: fatal error: libudev.h: No such file or directory
#include <libudev.h>_
          ^~~~~~~~~~~_
```

apt-get install libudev-dev
```
  CC       gresource.o
  CC       gicon.o
  CC       device_monitor.o
  CCLD     gtkterm
device_monitor.o: In function `device_monitor_thread':
device_monitor.c:63: undefined reference to `udev_new'
device_monitor.c:64: undefined reference to `udev_monitor_new_from_netlink'
device_monitor.c:71: undefined reference to `udev_monitor_enable_receiving'
device_monitor.c:88: undefined reference to `udev_device_unref'
device_monitor.c:77: undefined reference to `udev_monitor_receive_device'
device_monitor.c:81: undefined reference to `udev_device_get_devnode'
device_monitor.o: In function `device_monitor_handle':
device_monitor.c:51: undefined reference to `udev_device_get_action'
device_monitor.c:53: undefined reference to `udev_device_get_action'
collect2: error: ld returned 1 exit status
Makefile:404: recipe for target 'gtkterm' failed
```
after adding "-ludev" to src/Makefile, it compiles.

**Comment by wvdakker** [comment]
Check on libudev,h added in configure.ac

-ludev is already added if by running 'configure'. It is in the src/Makefile.am

**Comment by ddmesh** [comment]
this is strange, because I made a clean and called configure. 
but this didn't help.


On 21 June 2019 21:01:28 CEST, Willem van den Akker <notifications@github.com> wrote:
>Check on libudev,h added in configure.ac
>
>-ludev is already added if by running 'configure'. It is in the
>src/Makefile.am
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Jeija/gtkterm/issues/16#issuecomment-504537670

Freifunk Dresden
