### ISSUE TITLE
Configuration file honors locale

### ISSUE THREAD

**Issue by simonsso** [Jeija/gtkterm#17]
When login in to the same account with different locale settings cases a failure for gtkterm to read and save the configuration file. I traced this to be caused by the locate setting in use
(see also #10 which could be a duplicate of this)

**Steps to reproduce error** 
delete exiting  .gtktermrc

 start with a locate using comma as number separator

            
`LC_NUMERIC="en_DK.UTF-8"      gtkterm`
 save configuration and move it to temporary location 
`mv .gtktermrc .gtktermrc_dk`

restart with a locate which have dot as decimal separator
`LC_NUMERIC="en_US.UTF-8"      gtkterm`

Compare files
` meld .gtktermrc .gtktermrc_dk `

**Expected result:**
The configuration file created with the other locate should be identical and thus readable.

**Actual result:**
The results shows one file with decimal comma and one file with decimal dots starting gtkterm with a configuration file not matching current locate will result in a failure to read the settings.

**Suggested solution**
1 save values in configuration file independently from locale.
2 if reading config in updated format fails try to reread with current locate to be compatible with older config files.

Version on Ubuntu
```
$ dpkg -l gtkterm 
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                Version                        Architecture                   Description
+++-===================================================-==============================-==============================-===========================================================================================================
ii  gtkterm                                             0.99.7+git9d63182-1            amd64                          simple GTK+ serial port terminal


```

**Comment by wvdakker** [comment]
Can you try the last version in the repos?
The locale is set there.

**Comment by simonsso** [comment]
It is corrected now, in latest version. The version shipped with Ubuntu is very old
