### ISSUE TITLE
Packaging Debian

### ISSUE THREAD

**Issue by wvdakker** [Jeija/gtkterm#2]
Hi,

I am the new maintainer for the Debian package gtkterm. I want to use your respository as upstream source. Are you still kind of active in developing gtkterm?

If not, I like to use my fork as upstream base if that is ok with you.

/Willem

**Comment by Jeija** [comment]
I'm not really active in developing gtkterm, but I will make sure gtkterm compiles as I'm still actively using it. Using your fork of my repo as the upstream source sure is okay with me. Alternatively, I have also just added you as a collaborator to this repository, so feel free to use this repo as the upstream source and push updates to it yourself as needed for Debian.

**Comment by Jeija** [comment]
Also, just in case you happen to be interested in actually writing a "clean" implementation of a serial port terminal, I've been working on a minimal GTK+ Serial Port Terminal written in vala: https://github.com/Jeija/espterm. I've tried to keep the serial port functionality (`serial.vala`) as generic as possible.

The only issue with espterm is that the GUI is missing features that the underlying serial port code supports (it's mostly targeted at ESP8266 development). I would have prefered to maintain gtkterm instead of writing a whole new application from scratch, but the codebase is just too out-of-date and the mix of English and French made the code very hard to read for me as a non-native French and non-native English speaker.

**Comment by wvdakker** [comment]
On Wed, 2017-11-15 at 18:31 +0000, Florian Euchner wrote:
> Also, just in case you happen to be interested in actually writing a
> "clean" implementation of a serial port terminal, I've been working
> on a minimal GTK+ Serial Port Terminal written in vala: https://githu
> b.com/Jeija/espterm. I've tried to keep the serial port functionality
> (serial.vala) as generic as possible.
> 
> The only issue with espterm is that the GUI is missing features that
> the underlying serial port code supports (it's mostly targeted at
> ESP8266 development). I would have prefered to maintain gtkterm
> instead of writing a whole new application from scratch, but the
> codebase is just too out-of-date and the mix of English and French
> made the code very hard to read for me as a non-native French and
> non-native English speaker.
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/Jeija/gtk
> term","title":"Jeija/gtkterm","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in GitHub","url":"https://gi
> thub.com/Jeija/gtkterm"}},"updates":{"snippets":[{"icon":"PERSON","me
> ssage":"@Jeija in #2: Also, just in case you happen to be interested
> in actually writing a \"clean\" implementation of a serial port
> terminal, I've been working on a minimal GTK+ Serial Port Terminal
> written in vala: https://github.com/Jeija/espterm. I've tried to keep
> the serial port functionality (`serial.vala`) as generic as
> possible.\r\n\r\nThe only issue with espterm is that the GUI is
> missing features that the underlying serial port code supports (it's
> mostly targeted at ESP8266 development). I would have prefered to
> maintain gtkterm instead of writing a whole new application from
> scratch, but the codebase is just too out-of-date and the mix of
> English and French made the code very hard to read for me as a non-
> native French and non-native English
> speaker."}],"action":{"name":"View Issue","url":"https://github.com/J
> eija/gtkterm/issues/2#issuecomment-344685099"}}}

Yes I noticed the respository.

/Willem

**Comment by wvdakker** [comment]
On Wed, 2017-11-15 at 18:18 +0000, Florian Euchner wrote:
> I'm not really active in developing gtkterm, but I will make sure
> gtkterm compiles as I'm still actively using it. Using your fork of
> my repo as the upstream source sure is okay with me. Alternatively, I
> have also just added you as a collaborator to this repository, so
> feel free to use this repo as the upstream source and push updates to
> it yourself as needed for Debian.
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/Jeija/gtk
> term","title":"Jeija/gtkterm","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in GitHub","url":"https://gi
> thub.com/Jeija/gtkterm"}},"updates":{"snippets":[{"icon":"PERSON","me
> ssage":"@Jeija in #2: I'm not really active in developing gtkterm,
> but I will make sure gtkterm compiles as I'm still actively using it.
> Using your fork of my repo as the upstream source sure is okay with
> me. Alternatively, I have also just added you as a collaborator to
> this repository, so feel free to use this repo as the upstream source
> and push updates to it yourself as needed for
> Debian."}],"action":{"name":"View Issue","url":"https://github.com/Je
> ija/gtkterm/issues/2#issuecomment-344681541"}}}

No problem using your respository as base. 
I noticed several gtkterm respositories. There are many patches which
we can backport.

/Willem

**Comment by wvdakker** [comment]
On Wed, 2017-11-15 at 18:31 +0000, Florian Euchner wrote:
> Also, just in case you happen to be interested in actually writing a
> "clean" implementation of a serial port terminal, I've been working
> on a minimal GTK+ Serial Port Terminal written in vala: https://githu
> b.com/Jeija/espterm. I've tried to keep the serial port functionality
> (serial.vala) as generic as possible.
> 
> The only issue with espterm is that the GUI is missing features that
> the underlying serial port code supports (it's mostly targeted at
> ESP8266 development). I would have prefered to maintain gtkterm
> instead of writing a whole new application from scratch, but the
> codebase is just too out-of-date and the mix of English and French
> made the code very hard to read for me as a non-native French and
> non-native English speaker.
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/Jeija/gtk
> term","title":"Jeija/gtkterm","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in GitHub","url":"https://gi
> thub.com/Jeija/gtkterm"}},"updates":{"snippets":[{"icon":"PERSON","me
> ssage":"@Jeija in #2: Also, just in case you happen to be interested
> in actually writing a \"clean\" implementation of a serial port
> terminal, I've been working on a minimal GTK+ Serial Port Terminal
> written in vala: https://github.com/Jeija/espterm. I've tried to keep
> the serial port functionality (`serial.vala`) as generic as
> possible.\r\n\r\nThe only issue with espterm is that the GUI is
> missing features that the underlying serial port code supports (it's
> mostly targeted at ESP8266 development). I would have prefered to
> maintain gtkterm instead of writing a whole new application from
> scratch, but the codebase is just too out-of-date and the mix of
> English and French made the code very hard to read for me as a non-
> native French and non-native English
> speaker."}],"action":{"name":"View Issue","url":"https://github.com/J
> eija/gtkterm/issues/2#issuecomment-344685099"}}}

I also noticed the French in the code. 
Steps I had in mind:
1:	update code to make it ready for Debian packaging.
	The previous maintainer has orphaned the package and is still
the GTK2
	version.
2:	Apply patches from the several gtkterm respositories on
GitHub.
3:	Enhance the software (if needed).

For now I have do dive into the Autotools util. Therefor I have pulled
back the
commits and recommit them.

/Willem

**Comment by wvdakker** [comment]
I have used this respository as base for packaging in Debian.
