### ISSUE TITLE
Does device monitoring break BSD builds?

### ISSUE THREAD

**Issue by Jeija** [Jeija/gtkterm#20]
I haven't tested this, but gtkterm used to be compatible with the BSDs. With the addition of device monitoring, we added a dependency on `udev` which is only available on Linux.
Maybe we should optionally check for `udev` instead and build the device monitor feature only if `udev` is present [like we can do for Linux's serial.h](https://github.com/Jeija/gtkterm/blob/2ebc7ed64eee21b42fb0cb2355f7a91504a03f80/meson.build#L26) that is required for arbitrary baud rates?

**Comment by wvdakker** [comment]
Yes you are right, check is necessary for portability.
I will dive into it after my vacation.

**Comment by phako** [comment]
FWIW, you can get a FreeBSD CI runner on Cirrus. The others I haven't found so far
