### ISSUE TITLE
Merge features from Sellerie

### ISSUE THREAD

**Issue by Jeija** [Jeija/gtkterm#21]
I recently found this project called [Sellerie](https://github.com/phako/Sellerie/), which basically branched off from GTKTerm a couple of years ago. There was not a ton of development on GTKTerm during that time, but I collected a bunch of patches people wrote, added my own and pushblished it on GitHub. [Since 2017](https://github.com/Jeija/gtkterm/issues/2) this repository is Debian's upstream for GTKTerm with @wvdakker as Debian's package maintainer.

From a purely technical point of view, Sellerie it appears to be a lot more modern than GTKTerm in multiple ways. E.g., I also took some of the code for the meson build system PR (#19) from there.

Here is a quick, incomplete comparison of GTKTerm and Sellerie:
**Sellerie**

* Uses Glade UI files for basically everything
* Some bugfixes over original GTKTerm
* Somewhat cleaner architecture, just a bit of strange French-lanuage code form original GTKTerm
* Much more modern (e.g. no use of deprecated GtkStock, ...)
* Hardly known at all

**GTKTerm**

* Uses a lot of deprecated GTK / VTE functions
* Basic architecture unchanged from original GTKTerm, some strange French-language code
* Some bugfixes over original GTKTerm
* More locales (German + Russian)
* Device monitoring feature
* Relatively well-known, a lot of users (probably more users than we might think, since GTKTerm is something that many people use without thinking very much about it)

My takeaway form this would be that we should maybe start looking into Selliere and think about porting some of the improvements over to GTKTerm / merging the two projects. I would personally suggest that the `GTKTerm` name should remain given that it is more well-known, but I'm also happy to have my opinion changed.
From a licensing point of view this is certainly possible (both GPLv3), but before doing any of that I would like to know @phako's (Sellerie author) opinion on this matter and what he suggests. Of course we will have to credit @phako's work appropriately.

Any thoughts?

**Comment by phako** [comment]
Yes the forking history was a bit unfortunate, sorry.

I'm perfectly fine with you taking some code or even merging the two projects.

I also should probably also publish my UI refresher mocks somewhere.

**Comment by wvdakker** [comment]
@Jeija, yes you are right we can use a uplift for gtkterm. I also agree the name gtkterm is preferable, just because renaming would take some unnecessary Debian (and derivatives) transition work.

Perhaps cherrypicking improvements would be easiest?
