### ISSUE TITLE
Add support for disconnect/reconnect via CLI resp. signals

### ISSUE THREAD

**Issue by the0ne** [Jeija/gtkterm#26]
Hi,

I always wished to have a command-line interface for gtk-term so that I could - from a script - disconnect, flash the usb-device and then reconnect the terminal.
I thought about using signals USR1 (connect) and USR2 (disconnect) but never found the time to start implementation.

What do you think about this proposal?

**Comment by Jeija** [comment]
Merged as 2511ec23a060c78540593913034a8027b9482cdb
