### ISSUE TITLE
delete only the scrollback

### ISSUE THREAD

**Issue by the0ne** [Jeija/gtkterm#32]
It often happens I don't want to clear the screen but only the scrollback.
Turns out from program point of view, this would be very simple - in `term_config.c` I have added:
```
void clear_scrollback(void){
	vte_terminal_set_scrollback_lines (VTE_TERMINAL(display), 0);
	vte_terminal_set_scrollback_lines (VTE_TERMINAL(display), term_conf.scrollback);
}
```
Would be fantastic if you could add a menu item which calls this function!

**Comment by wvdakker** [comment]
Added
