### ISSUE TITLE
Partial localization translation does not display

### ISSUE THREAD

**Issue by yjwork-cn** [Jeija/gtkterm#33]
Version: 1.0.1
Operating system and version: Debian GNU/Linux bullseye/sid
debian:~$ locale
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN:zh
It can display normally in ver.0.99.7
Can you update the potfiles.in and pot file?
Thanks!

**Comment by wvdakker** [comment]
Hi,

Which part does not show translated? 

/Willem

**Comment by yjwork-cn** [comment]
![截图_2019-12-26_07-45-40](https://user-images.githubusercontent.com/53205242/71451552-d38bb880-27b3-11ea-8c6c-eee10ed6204b.png)
![截图_2019-12-26_07-45-19](https://user-images.githubusercontent.com/53205242/71451553-d4244f00-27b3-11ea-9a2d-e712b0030f66.png)
![截图_2019-12-26_07-44-45](https://user-images.githubusercontent.com/53205242/71451554-d4244f00-27b3-11ea-8502-2e47a17d19c1.png)
![截图_2019-12-26_07-44-10](https://user-images.githubusercontent.com/53205242/71451555-d4244f00-27b3-11ea-8a4b-1308f06b76bb.png)

**Comment by yjwork-cn** [comment]
Popup Window：
"configuration"
"configure macros"
"load configuration"
"about GTKterm"

**Comment by wvdakker** [comment]
Updated
