### ISSUE TITLE
Baudrate 1500000

### ISSUE THREAD

**Issue by fransvanberckel** [Jeija/gtkterm#34]
Working on Linux ports, with TTL on Rockchip boards, i need 1,500,000 baud/s with 8N1.

- https://www.google.com/search?q=1500000+baud+ttl
- https://crwulff.blogspot.com/p/rock64-serial.html

#USB-TTL #UART #Serial Adapter-microcontroller

**Comment by Jeija** [comment]
Does it work if you enter the baudrate manually? If so, it's just a matter of adding it as another default.

**Comment by fransvanberckel** [comment]
No, it does not. But if i close gtkterm, and open minicom. Setting the port & speed, it runs!

**Comment by wvdakker** [comment]
The program has 2 options with those excessive speeds. 1000000 and 2000000. I dont know if your device can put on 1000000, but that should be helpful to detect the failure.

If you put it on curstom 1500000 as you noted in previous message can you confirm that the interface shows the right speed (not truncated or so)?

**Comment by fransvanberckel** [comment]
That's what i did try. And be sure your TTL board supports 1,500,000 baud/s.

**Comment by wvdakker** [comment]
Ok to summarize ...
gtkterm does not work with the predefined 1000000 and 2000000 baud rates.
Minicom however does work with these baud rate.

Ergo: probably the software does not handle very large speeds.

Correct?

**Comment by Jeija** [comment]
I think the reason might be that for some default speeds (e.g. 115200, 9600, ... baud) we use a different mechanism to configure the hardware than for unknown speeds - 1500000 is one of these unknown baud rates for us.

Look at https://github.com/Jeija/gtkterm/blob/master/src/serial.c#L178 for instance. If the speed is unknown, we call `set_custom_speed(config.vitesse, serial_port_fd);`.
Minicom, on the other hand, handles some additional baud rates: https://github.com/Distrotech/minicom/blob/54202fe0ea8510dc8fcd23ab49d39d3d8cb2e529/src/sysdep1.c#L394. This includes the `B1500000` baud rate.

**Comment by Jeija** [comment]
@fransvanberckel : I just pushed a (minimal, see https://github.com/Jeija/gtkterm/commit/80345e14f47ef10ab5bff95d500c358a50826d2a) change to the `fix34` branch. Could you test it and see if it resolves your issue?

**Comment by sharkcz** [comment]
@Jeija, I have found this issue recently and tested the proposed fix on my rk3399 device (Pinebook Pro) that requires the 1500000 speed and it works. Without the patch and only manually specifying the speed, there was garbage on the screen. Please merge it. The USB/serial adapter is "QinHeng Electronics CH340 serial converter" sold as accessory with PBP.

**Comment by Jeija** [comment]
@sharkcz Thanks for the information. I will merge this later today.

**Comment by Jeija** [comment]
I have merged https://github.com/Jeija/gtkterm/commit/80345e14f47ef10ab5bff95d500c358a50826d2a as https://github.com/Jeija/gtkterm/commit/0585172764f3872b8c1cdcd1da604fe28f69d873. Again, thanks for the report, closing this issue now.
