### ISSUE TITLE
Configuration file should be in XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by BrunoVernay** [Jeija/gtkterm#40]
The configuration file is written to $HOME/.gtktermrc
Configuration file should be in XDG_CONFIG_HOME 
See  https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
$XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

**Comment by tinywrkb** [comment]
Related: [get_user_config_dir](https://docs.gtk.org/glib/func.get_user_config_dir.html) and [GNOME Goal: XDG Base Directory Specification Usage](https://wiki.gnome.org/Initiatives/GnomeGoals/XDGConfigFolders).

**Comment by Jeija** [comment]
Sorry for being silent on this issue so far. I have just created a commit fe66238bce24e923fcc4a4876296f4dde755d2cd on a feature branch that will change the default location of the configuration file.

It is important to me to stay backward-compatible, many people may have old `.gtktermrc` lying around in their home directories. Therefore, fe66238bce24e923fcc4a4876296f4dde755d2cd will move any potentially existing configuration file from `$HOME` to `$XDG_CONFIG_HOME` at launch. I'll have to discuss what this means for Flatpak compatibility and will then soon merge that commit. Let me know if you have any comments / suggestions regarding that behavior.

**Comment by Jeija** [comment]
I closed this issue now that fe66238bce24e923fcc4a4876296f4dde755d2cd is merged. Thanks for reporting!
