### ISSUE TITLE
No module named 'pqcom_serial'

### ISSUE THREAD

**Issue by piLinux** [Jeija/gtkterm#43]
I believe the following error message is self-explanatory. Any help would be appreciated!

**OS:** `Ubuntu 20.04`
**Python:** `3.8.10`
*Note:* I installed `PyQt5` and `pqcom` in a virtual environment

```
Traceback (most recent call last):
  File "/path/to/pythonvenv/my_env/bin/pqcom", line 5, in <module>
    from pqcom.pqcom import main
  File "/path/to/pythonvenv/my_env/lib/python3.8/site-packages/pqcom/pqcom.py", line 41, in <module>
    import pqcom_serial
ModuleNotFoundError: No module named 'pqcom_serial'
```

**Comment by wvdakker** [comment]
Hi,

And how is this related to gtkterm?
Are you calling gtkterm from a python script and redirecting the comm
port?

/Willem

**Comment by piLinux** [comment]
Sorry, I created the issue in the wrong repository! I was testing different serial tools and posted the issue here by mistake.
Thanks for your prompt response.
