### ISSUE TITLE
No status change when port get disconnected (USB Serial).

### ISSUE THREAD

**Issue by Pe3ucTop** [Jeija/gtkterm#6]
Hello, 
Thanks for good app, but often ttyUSB could be disconnected/reconnected and would be nice to see this in status and may be to have auto-reconnect option.
By now when there is no response from serial I trying to press F5 (OpenPort) even I'm not sure was it disconnected or not.

**Comment by wvdakker** [comment]
Yes, you are correct. Detecting a lost serial connection is something on the wish list.
Hopefully we can add this function in a short time.

Thanks.
Willem

**Comment by wvdakker** [comment]
Added in autoreconnect branch.
