### ISSUE TITLE
"Send RAW file" command not working!

### ISSUE THREAD

**Issue by misari03** [Jeija/gtkterm#8]
If i select "send raw file" and enter a file, only the first packet will be sent and no further transmission will occur.
At the end of the ecriture() function in files.c, when I insert the line -- printf ("\ r"); --, it works normally.
I do not know why.

![2018-11-26 19-18-46](https://user-images.githubusercontent.com/16631392/49007993-26113480-f1b0-11e8-98f8-e2aaf6d7022a.png)

**Comment by wvdakker** [comment]
And if you use the "end of file delay' in configuration option?
Try to set it on 1 or 2 ms. Normally that helps.

**Comment by wvdakker** [comment]
Any feedback?
