### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by cg31** [Jeija/gtkterm#9]
I got a Hikey 970, it is using ftdi serial, and its serial port is showing as /dev/ttyXRUSB0.

So it would be better to add it to devices list for check:

diff --git a/src/term_config.c b/src/term_config.c
index b25d3fa..3675115 100644
--- a/src/term_config.c
+++ b/src/term_config.c
@@ -59,6 +59,7 @@ gchar *devices_to_check[] =
        "/dev/ttyS%d",
        "/dev/tts/%d",
        "/dev/ttyUSB%d",
+       "/dev/ttyXRUSB%d",
        "/dev/ttyACM%d",
        "/dev/usb/tts/%d",
        NULL

**Comment by wvdakker** [comment]
Added.
